name: Vote open

on:
  schedule:
    - cron: '0 14  *  *  3'
  workflow_dispatch:
    branches: [ main ]

# Discord message options
# see: https://github.com/Ilshidur/action-discord
# see: https://birdie0.github.io/discord-webhooks-guide/discord_webhook.html
env:
  COLORS: ("" "26367" "16750848" "65433" "10027263")
  AVATAR: https://raw.githubusercontent.com/the-au-forml-lab/plgroup/main/.github/assets/vote.png
  USERNAME: "PL Reading Group Paper Vote"
  NOW: $(date +'%d %B')

jobs:
  vote_options:
    # Sequentially generate suggestions, if paper vote is enabled
    if: ${{ vars.PAPER_VOTE_ON == 1 }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        options: [1] #, 2, 3, 4]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: 🔮 Choose random paper
        run: npm run choose
      - name: 📝 Update website
        run: npm run web
      - name: ✅ Commit paper selection changes
        run: bash ${PWD}/.github/utils/commit.sh
      - name: 🔎 Lookup selection details
        id: vars
        run: |
          array=${{ env.COLORS }}
          echo "color=${array[${{ matrix.options }}]}" >> $GITHUB_OUTPUT
          echo "title=$(bash .github/utils/title.sh)" >> $GITHUB_OUTPUT
          echo "body=\"$(bash .github/utils/pr.sh)\"" >> $GITHUB_OUTPUT
          echo "abs=$(bash .github/utils/abs.sh)" >> $GITHUB_OUTPUT
      - name: 🔖️ Create a pull request
        id: paperpr
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: files/*.txt
          labels: paper-vote,next-paper
          branch: paper-vote-${{ matrix.options }}
          title: ${{ steps.vars.outputs.title }}
          body: ${{ fromJSON(steps.vars.outputs.body) }}
          delete-branch: true
      - name: 🗳️ Post vote option to Discord
        uses: Ilshidur/action-discord@master
        if: ${{ env.DISCORD_WEBHOOK != '' }}
        env:
          DISCORD_AVATAR: ${{ env.AVATAR }}
          DISCORD_USERNAME: ${{ env.USERNAME }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_EMBEDS: '[{ "color":"${{ steps.vars.outputs.color }}", "title":"${{ steps.vars.outputs.title }}", "description":"${{ steps.vars.outputs.abs }} [Merge PR ${{ steps.paperpr.outputs.pull-request-number }}](${{ steps.paperpr.outputs.pull-request-url }})" }]'
        with:
          args: "**Vote option ${{ matrix.options }} | ${{ env.NOW }}**"

  post_actions:
    needs: vote_options
    runs-on: ubuntu-latest
    steps:
      - name: 🧑‍🏫 Post voting instructions
        uses: Ilshidur/action-discord@master
        if: ${{ env.DISCORD_WEBHOOK != '' }}
        env:
          DISCORD_AVATAR: ${{ env.AVATAR }}
          DISCORD_USERNAME: ${{ env.USERNAME }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: "**Voting Instructions.**\n- Rank papers using number reactions :one: favorite — :four: least favorite.\n- Any participant may volunteer to be the **discussion leader** by selecting a paper from the current pool and announcing this to the group (use :coin:). In this case, the vote is void and the paper selected by the discussion leader is selected automatically.\n- Vote concludes by merging the PR of the selected paper."
